apiVersion: v1
kind: PersistentVolume
metadata:
  name: fuse-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  storageClassName: parallel-dynamic-runtime-fuse-storage-class
  claimRef:
    namespace: fuse-ns
    name: fuse-pvc
  mountOptions:
    - implicit-dirs
  csi:
    driver: gcsfuse.csi.storage.gke.io
    volumeHandle: parallel-dynamic-runtime-fuse
    readOnly: true
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fuse-pvc
  namespace: fuse-ns
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: fuse-pv
  storageClassName: parallel-dynamic-runtime-fuse-storage-class
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cs-fuse-demo-app
  namespace: fuse-ns
  annotations:
    iam.gke.io/gcp-service-account: fuse-sa@parallel-dynamic-runtime-tf.iam.gserviceaccount.com
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cs-fuse-demo-app
  name: cs-fuse-demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cs-fuse-demo-app
  template:
    metadata:
      labels:
        app: cs-fuse-demo-app
      annotations:
        gke-gcsfuse/volumes: "true" #Required
        #Optional resource configuration for the sidecar container. Allocate more CPU to the sidecar container if your workloads need higher throughput.
        gke-gcsfuse/cpu-limit: 500m
        gke-gcsfuse/memory-limit: 100Mi
        gke-gcsfuse/ephemeral-storage-limit: 5Gi   
    spec:
      serviceAccountName: fuse-ksa
      securityContext:
        runAsUser: 1001
        runAsGroup: 2002
        fsGroup: 3003
      volumes:
      - name: fuse-static
        persistentVolumeClaim:
          claimName: fuse-pvc
      containers:
      - image: busybox:latest
        name: busybox
        command: ["sleep"]
        args: ["infinity"]
        volumeMounts:
        - name: fuse-static
          mountPath: /data
          readOnly: true
# ---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: fuse-application
#   namespace: fuse-ns
#   annotations:
#     gke-gcsfuse/volumes: "true"
# spec:
#   containers:
#   - image: us-central1-docker.pkg.dev/parallel-dynamic-runtime-tf/artifact-registry/busybox:latest
#     name: fuse-application-container
#     command: ["sleep"]
#     args: ["infinity"]
#     volumeMounts:
#     - name: fuse-static
#       mountPath: /mountpath
#       readOnly: true
#   serviceAccountName: fuse-ksa
#   volumes:
#   - name: fuse-static
#     persistentVolumeClaim:
#       claimName: fuse-pvc